### PR TITLE
Use data when using requests library

### PR DESCRIPTION
**Pull request by chmouel**

### CODE REVIEW

**Comment by reidrac** [comment]
Looks good but I wonder if we can do it a way so we don't raise an exception in every request.

**Comment by chmouel** [comment]
sure, I was going to argue that it doesn't make much difference from a benchmarking perspective than doing method introspection but I was wrong it does makes a difference, since try/expect is much more expensive, i.e: http://pastie.org/private/tmdmk7oztwowh0k6efjkg which results with http://pastie.org/private/olbljb1coamevv7jqoxfq, will do it properly

**Comment by chmouel** [comment]
ah that pull request should go to cloudfs/ftp-cloudfs, no or did I mess it? (I am so used by gerrit these days that I don't know how to use github anymore 8-))

**Comment by reidrac** [comment]
Looks better! :)

**Comment by reidrac** [comment]
Oh, you're right! I didn't realize we were in the wrong repository! :D

**Comment by reidrac** [comment]
Should be in https://github.com/cloudfs/ftp-cloudfs ; and your repo should be a README pointing to the new location.

To be honest, I think that redirection was confusing anyway (this pull request proves it!).

**Comment by chmouel** [comment]
Ok I have pushed the changes to cloudfs/ftp-cloudfs and update the repo with the README, I maybe need to delete that repo but i'm not sure how I can contribute then?

**Comment by reidrac** [comment]
I think you can't delete it.

May be you could transfer the ownership to the organization so we don't use a fork as main repo; and then you can have your own fork.

I'm not sure what's best.

**Pull request merged**
