### PR TITLE
add the logrotate file

### PR DESCRIPTION
**Pull request by c35sys**
Forgot to add it previously

### CODE REVIEW

**Comment by reidrac** [comment]
I prefer using syslog directly with --syslog instead of --log-file.

Can we include a note about that? May be including a README.Debian in the deb would be a good idea.

**Comment by c35sys** [comment]
I added the README.Debian file, is that ok for you ?

**Comment by reidrac** [comment]
Perfect!

The flag looks OK to me (the group is daemon anyway).

Thank you!

**Comment by c35sys** [comment]
Thanks !

**Pull request merged**
