### PR TITLE
Iterate over keys of multiprocessing Manager, instead itself.

### PR DESCRIPTION
**Pull request by rocco66**
See http://bugs.python.org/issue9733
and strange trace:

```
2012-08-29 18:19:15,042 - ERROR - ftpcloudfs[1251]: Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/pyftpdlib/ftpserver.py", line 3812, in handle_accept
    handler.handle_error()
  File "/usr/lib/pymodules/python2.6/pyftpdlib/ftpserver.py", line 2339, in handle_error
    self.close()
  File "/usr/lib/pymodules/python2.6/ftpcloudfs/monkeypatching.py", line 82, in close
    if self.remote_ip in self.shared_ip_map:
  File "", line 2, in __contains__
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 740, in _callmethod
    raise convert_to_error(kind, result)
RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 216, in serve_client
    obj, exposed, gettypeid = id_to_obj[ident]
KeyError: '7fd358003a00'
```

### CODE REVIEW

**Comment by reidrac** [comment]
That's amazing, how is that I can't reproduce that? :)

I tried Python 2.7.3 and Python 2.6.6. Can you tell me which Python version are you running?

**Comment by reidrac** [comment]
For example:

``` python
# python
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocessing import Manager
>>> m = Manager()
>>> d = m.dict()
>>> d['127.0.0.1'] = 1
>>> '127.0.0.1' in d
True
>>> '127.0.0.2' in d
False
>>> 
```

**Comment by rocco66** [comment]
Sorry, I think it is some race. It were concurrents requests. Python 2.6.5
I done many file requests ("while true" loop in bash with wget&) on test machine and get one time some similar:

```
2012-08-21 14:29:08,321 - ERROR - ftpcloudfs[2531]: [7091_7091]@188.93.16.50:27567 
unhandled exception in instance <ftpcloudfs.monkeypatching.MyFTPHandler object at 0
xda6f90>
Traceback (most recent call last):
  File "/usr/lib/python2.6/asyncore.py", line 76, in read
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 416, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.6/asynchat.py", line 110, in handle_read
    data = self.recv (self.ac_in_buffer_size)
  File "/usr/lib/python2.6/asyncore.py", line 369, in recv
    self.handle_close()
  File "/usr/local/lib/python2.6/dist-packages/pyftpdlib-0.7.0-py2.6.egg/pyftpdlib/
ftpserver.py", line 2342, in handle_close
    self.close()
  File "/usr/local/lib/python2.6/dist-packages/ftp_cloudfs-0.14-py2.6.egg/ftpcloudf
s/monkeypatching.py", line 85, in close
    self.shared_ip_map[self.remote_ip] -= 1
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 740, in _callmethod
    raise convert_to_error(kind, result)
KeyError: '188.93.16.50'
```

**Comment by reidrac** [comment]
The problem with using dict.keys() is that it's not very efficient because it returns a copy of the dictionary's list of keys, and if it is a race condition it won't fix the problem.

We should review the lock code. It's not brilliant anyway.

**Comment by reidrac** [comment]
Can you try this patch?

https://github.com/reidrac/ftp-cloudfs/commit/daa9210857d333e6e87c2180cd57139d73f1e313

**Comment by reidrac** [comment]
I'm trying with workers = 10, max-cons-per-ip = 5 and 1000 concurrent clients from the same IP and I can't reproduce the problem with the un-patched code (Python 2.7.3 and 2.6.6).

**Comment by reidrac** [comment]
OK, got it! 5 workers and 5 connections per IP and I reproduced it with Python 2.6.6 (not with Python 2.7.3 though).

My proposed patch seems to fix the problem.

**Comment by reidrac** [comment]
I've committed the fix, thanks for your report!

**Comment by rocco66** [comment]
Thanks for fix :)

**Pull request closed without merging**
