### PR TITLE
Compatibility!

### PR DESCRIPTION
**Pull request by ncw**
Thanks pulling my last changes :-)

Here are some more!

These are minor fixes, tidies :-
- commit 12d7335f2249e3435b591f0ee7cf53d05710c3dc
  - Remove unnecessary code from MyDTPHandler
- commit fb4e357891d740066224f8cd5e9cca9139ade349
  - Make compatible with pyftpd >= 0.6
- commit 74957879766aa8db4e58c7183bbf6122200cc19b
  - Implement file modification times in RackspaceCloudFilesFS.stat
- commit a68caecd58ce33e0987f2832c9ec92c0711e58de
  - Fix crash if user doesn't have permissions to list containers
- commit 61d9f7fd9c03d09b987d2e42950b92ace840c22a
  - Add .gitignore to hide python and emacs cruft

This one is the most important one
- commit 98aad0ca54a565c7153e460509477eaad22c1973
  - Remove custom directory list routines and replace with a listdir cache to improve compatibility

Take a look at the commit message - hopefully it is self explanatory.  After this ftp-cloudfs is much more compatible (well it is as compatible as pyftpdlib which is very!)

Cheers

Nick

### CODE REVIEW

**Comment by chmouel** [comment]
Sounds good, will merge this and probably make a new release with all your fixes. Thanks a lot!

PS: About  61d9f7f I usually have that globally in ~/.gitignore  (see core.excludesfile)

**Comment by chmouel** [comment]
I have pulled the change and released it as 0.5, I have tested it and it works pretty well. Thanks again, you made me using this again as well ;-)

**Comment by ncw** [comment]
Thanks for merging and making a new release, oh and for the contributor mention ;-)

I have some more stuff I want to implement if I get the time
- if user logs in as user@container then change straight to container - useful for users with permissions for only one container
- investigate a file hierachy compatible with https://github.com/redbo/cloudfuse/ - not sure whether this is sensible or not
- daemonise and log to syslog

**Comment by chmouel** [comment]
Hey nick,

Great stuff, some comments on this :

What kind of user permission? There is none on a containner level in CloudFiles.

I haven't used redbo's cloudfuse so I am not sure what kind of file hierachy it has, if you are talking about this http://programmerthoughts.com/programming/nested-folders-in-cloud-files/ then yeah this definitively would be nice.

I was thinking about daemonize as well using python-demon(http://pypi.python.org/pypi/python-daemon/) which offer some goodies like chroot support.

Thanks a lot,
Chmouel.

**Comment by ncw** [comment]
User permissions: there are or can be in OpenStack depending on your auth model

Yes that is exactly what I meant.  It is also in the manual (see section Pseudo-Hierarchical Folders/Directories), so must be official ;-)
- http://docs.rackspacecloud.com/files/api/cf-devguide-latest.pdf 
- http://docs.openstack.org/openstack-object-storage/developer/content/ch03s02.html

python-daemon: not seen that before - will check it out!

**Comment by chmouel** [comment]
Sounds good, thanks!

**Pull request merged**
