### PR TITLE
Refactor Debian packaging using debhelper. 

### PR DESCRIPTION
**Pull request by c35sys**
Hi all,

I completely change the way to generate the deb file after the discussion with Juan (for sftpcloudfs).

I now use debhelper, I think it's a cleaner way than the previous one I used (the python way).

### CODE REVIEW

**Comment by reidrac** [comment]
It looks fine to me, but I can see a problem every time we make a new release: all the files referring to a VERSION will get outdated.

**Comment by reidrac** [comment]
Btw, in next pull request please include your name in the contributors list ;)

Thanks!

**Comment by c35sys** [comment]
About each new release, I think this can be accomplished in two ways:
- Modify version to the following files: debian/README.source and debian/changelog
  or
- add a new repo only with the debian directory ( as for swauth for example: https://github.com/gholt/swauth_debian)

Which one do you prefer ?

Also, are you interested by a wiki page to generate the debian package ?

**Comment by reidrac** [comment]
I really like the idea of including the debian stuff in the main repository. What about simply saying VERSION and put a note at the beginning? It's just that I don't want the release process to get overcomplicated.

Regarding the wiki, I think it's enabled... so go for it, although Chmouel may have the last word, this is his repository! :)

**Comment by c35sys** [comment]
You'll be happy, I just modified README.source to include a variable at the beginning.

Or, if I add the process in a wiki page, I can simply remove README.source, and put a link to that page in README.rst
In that way, only the debian/changelog will have to be modified for a new release.

**Pull request merged**
