### PR TITLE
override 10000 objects listing limit with markers

### PR DESCRIPTION
**Pull request by c35sys**
Hi,

One of our users is reaching the "10000 get response" limit when listing a container.
This patch overrides this limit using markers.

Note: the patch is working for us and works with sftpcloudfs as well.

Christophe

### CODE REVIEW

**Comment by reidrac** [comment]
The diff looks OK, but I'd appreciate if you could provide tests for the change.

**Comment by c35sys** [comment]
Ok, I'll try to write one ASAP.

**Comment by c35sys** [comment]
I used direct API for upload/delete because the test was too slow.
With direct API upload, I can run test in 42 min, better than 143 min with FTP upload.

**Comment by reidrac** [comment]
Thanks Christophe! I'll merge this change ASAP.

I'll try to make a mockup so we don't need to actually upload the file to test your code.

**Comment by c35sys** [comment]
Hi Juan, thanks for the update !

**Comment by reidrac** [comment]
I've merged your change!

I've written a couple of tests using mockup objects so we can verify ListDirCache without creating big amount of files (42 minutes test it's not practical I'm afraid).

The mockup is not complete and we must be careful if we want to use it for other tests (I tried to simulate enough features just to test your change). Please take a look and let me know what do you think (specially if I made something wrong :D).

Thanks for your contribution!

**Comment by c35sys** [comment]
Juan, I love the mockup tests. It's a very interesting way to do it.
And it works great by the way !

**Comment by reidrac** [comment]
Thanks! I'll release 0.14 next Monday.

**Pull request closed without merging**
