### PR TITLE
Hierachical file support

### PR DESCRIPTION
**Pull request by ncw**
Quite a lot of changes in this!  Highlights are
- Pseudo-hierachical folders/directories supported
- Containers show size in listings
- Logging in server module
- Attempt to catch and translate all cloudfiles errors with correct error numbers
- Rename support
- Lots of tests

See the commits for the full story!

### CODE REVIEW

**Comment by chmouel** [comment]
Awesome stuff, I had a quick code review and this all seems good.. I have uploaded 0.7 with your changes. Thanks a lot, again.

**Comment by ncw** [comment]
Great thanks!  I'm only testing against openstack BTW, so I hope it works with Rackspace Cloudfiles :-)

Cheers

Nick

**Comment by chmouel** [comment]
Yeah as far from  my quick testing it seemed to work aside of this bugs in pyftpdlibs http://code.google.com/p/pyftpdlib/issues/detail?id=159&colspec=ID%20Summary%20Type%20Status%20Priority%20Milestone%20Opened

**Comment by ncw** [comment]
Ah, interesting... I'd noticed cat wasn't working either, but I wasn't sure why.

I've fixed it now though and I'll open a pull request shortly

**Pull request merged**
